{% set version = "2.0.0" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-datefixr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/datefixR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/datefixR/datefixR_{{ version }}.tar.gz
  sha256: 08d3ea02e94eaf8dc922275507ba0f6daec7c64838cf27eae97cd4ebcffafb2a

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('cxx') }}            # [not win]
    - {{ compiler('m2w64_cxx') }}      # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-rcpp
    - r-lifecycle
    - r-rlang
    - r-stringr
  run:
    - r-base
    - r-rcpp
    - r-lifecycle
    - r-rlang
    - r-stringr

test:
  commands:
    - $R -e "library('datefixR')"           # [not win]
    - "\"%R%\" -e \"library('datefixR')\""  # [win]

about:
  home: https://docs.ropensci.org/datefixR/, https://github.com/ropensci/datefixR
  license: GPL-3.0-or-later
  summary: "There are many different formats dates are commonly represented with: the order of day, month, or year can differ, different separators (\"-\", \"/\", or whitespace) can be used, months can be numerical, names, or abbreviations and year given as two digits or four. 'datefixR' takes dates in all these different
    formats and converts them to R's built-in date class. If 'datefixR' cannot standardize a date, such as because it is too malformed, then the user is told which date cannot be standardized and the corresponding ID for the row. 'datefixR' also allows the imputation of missing days and months with user-controlled behavior."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
